repos:
  - repo: local
    hooks:
      - id: run-tox
        name: Run Tox
        entry: tox
        language: system
        pass_filenames: false
        stages:
          - push

      - id: commitizen
        name: commitizen check
        entry: cz check
        args: [--allow-abort, --commit-msg-file]
        stages: [commit-msg]
        language: system
        minimum_pre_commit_version: "1.4.3"

      - id: conventional-gitmoji
        name: gitmojify
        entry: gitmojify
        args: [--commit-msg-file]
        stages: [commit-msg]
        language: system
        minimum_pre_commit_version: "1.4.3"
